version: "3.7"                    

services:                         
  ptslab-mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: sqlserver-pts1
    restart: always
    hostname: mssql
    environment: 
      SA_PASSWORD: 122312asd #Thiết lập password
      ACCEPT_EULA: 'Y'
      # Express: 

    volumes:
      - mssqlvolume:/var/opt/mssql/data # thư mục lưu DB
      # - ./bk:/var/opt/mssql/backup
    ports:
      - "1433:1433"     
                        
volumes:                                
    mssqlvolume:        
      name: sqlserver-xtlab-vl
                    
  